#!/usr/bin/python

import time, sys

if len(sys.argv) != 3:
    sys.exit("./counter <start> <stop>")

start= int(sys.argv[1])
end = int(sys.argv[2])
while start <= end: 
    print("{0}".format(start))
    start += 1
    time.sleep(3)
